require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

AllCops:
  Exclude:
    - 'Gemfile'
    - 'bin/rake'
    - 'bin/setup'
    - 'config.ru'
    - 'config/**/*.rb'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/MethodLength:
  Max: 15

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/MultipleComparison:
  ComparisonsThreshold: 3

Style/Alias:
  EnforcedStyle: prefer_alias