services:
  web:
    build:
      context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-${UID:-1000}}
        - RUBY_VERSION
        - RAILS_MASTER_KEY
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=${RAILS_ENV:-production}
      - BUNDLE_WITHOUT=${BUNDLE_WITHOUT:-development:test}
      - BUNDLE_DEPLOYMENT=${BUNDLE_DEPLOYMENT:-1}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db/${POSTGRES_DB}
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready
      interval: 2s
      timeout: 5s
      retries: 30
