# frozen_string_literal: true

require_relative 'dom/node'
require_relative 'dom/node_list'
require_relative 'dom/character_data'
require_relative 'dom/text'
require_relative 'dom/comment'
require_relative 'dom/ruby_code'
require_relative 'dom/safe_text'
require_relative 'dom/attribute'
require_relative 'dom/elemental'
require_relative 'dom/element'
require_relative 'dom/html_element'
require_relative 'dom/html_void_element'
require_relative 'dom/document'

require_relative 'dom/tags'
require_relative 'dom/html_standard_tags'
require_relative 'dom/html_void_tags'
require_relative 'dom/html_builder'
require_relative 'dom/html_list_builder'
require_relative 'dom/html_compiler'
require_relative 'dom/element_builder'