module Dragnet
  class Reply < ApplicationRecord
    include Retractable

    def cached_answers: () -> untyped
    def answers_to: (untyped question) -> untyped
    def value: (untyped question) -> untyped
    def ensure_visit: (untyped visit) -> (untyped | nil)

    CSRF_TOKEN_PRECISION: 256
    EXPIRATION_DURATION: ActiveSupport::Duration

    def expired?: (?ActiveSupport::TimeWithZone now) -> bool
    def submitted!: (ActiveSupport::TimeWithZone timestamp) -> self
    def submit: (Hash[Symbol | String, untyped] attributes, ?timestamp: ActiveSupport::TimeWithZone) -> (false | self)
    def submit!: (Hash[Symbol | String, untyped] attributes, ?timestamp: ActiveSupport::TimeWithZone) -> void

    private

    def perform_submission: (Hash[Symbol | String, untyped] attributes, ActiveSupport::TimeWithZone timestamp) -> void
  end
end
