module Dragnet
  # An individual edit to a survey
  class SurveyEdit < ApplicationRecord
    def applied?: () -> bool
    def applied!: (?ActiveSupport::TimeWithZone timestamp) -> self
    def apply: (?ActiveSupport::TimeWithZone timestamp) -> (self | false)
    def apply!: (?ActiveSupport::TimeWithZone timestamp) -> self
  end
end
